### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [kalliope-project/kalliope-app#25]
F-Droid maintainer here. We received [a request](https://gitlab.com/fdroid/rfp/issues/492) to include your app with our catalogue. Hoping you're not opposed to that: in order to fulfill that wish, we'd need the Android project is included in the repository, otherwise we cannot build Cordova/Ionic apps. Could you help us with that? Thanks in advance!

**Comment by Sispheor** [comment]
Hi, what do you mean by Android Project? The build?

**Comment by IzzySoft** [comment]
I'm no dev, so I just [forward this](https://gitlab.com/fdroid/rfp/issues/492#note_74037704). IIRC it's some folder named `project/android/` (or the other way around?).

**Comment by Sispheor** [comment]
The fact is that usually you don't push built stuff in git. Maybe we can push it in a non linked branch like for the build of a GitHub page, what do you think?

**Comment by IzzySoft** [comment]
A git submodue should do IMHO. I doubt a Github page would do. @rudloff could say for sure.

**Comment by Sispheor** [comment]
I was not saying that a github page would do the job. I proposed to copy the model of using a dedicated branch to provide the built part. This is how Github pages work, you need to push in a branch called "gh-page" which is not related to a branch of the project.
The fact is that we don't want to add built stuff in our main branch.

**Comment by Rudloff** [comment]
I think  @Sispheor meant an alternative branch like what is used for GitHub pages, not an actual GitHub page.
We can certainly use a different branch than master, but it would help to have tags pointing to that so we know which commits to package.

**Comment by Sispheor** [comment]
@LaMonF

**Comment by LaMonF** [comment]
@Rudloff @IzzySoft 
I just made a specific branch with the android platform (is it what you expect ?). You can find the `/android` repo following this link : 
https://github.com/kalliope-project/kalliope-app/tree/F-Droid/kalliope/platforms/android

I also created a tag as you required : https://github.com/kalliope-project/kalliope-app/releases/tag/F-Droid-0.1

**Comment by Rudloff** [comment]
That is exactly what we need, thanks!

**Comment by Rudloff** [comment]
I think I spoke too soon.
The app builds correctly but crashes with this error:
```
02-03 17:19:43.818  8042  8077 E AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/www/index.html
```
I think the `kalliope/platforms/android/app/src/main/assets/www/` folder is missing.

**Comment by LaMonF** [comment]
@Rudloff Ok www/ was still in the gitignore .... 
I updated the branch and the tag. It should be fine now :)

**Comment by Rudloff** [comment]
Yes, it works correctly now. Thank you!

**Comment by Rudloff** [comment]
I noticed two problems with the [cordova-plugin-geofence](https://github.com/cowbell/cordova-plugin-geofence) plugin you are using:
* It contains a [prebuilt gson library](https://github.com/kalliope-project/kalliope-app/tree/F-Droid/kalliope/platforms/android/app/libs) and we require everything to be built from source. (But that it not a huge issue, it is pretty easy for us to rebuild this library.)
* It [requires Play Services](https://github.com/kalliope-project/kalliope-app/blob/04ad05adf9ac273bd958f5334bdde132d3a0fd79/kalliope/platforms/android/app/build.gradle#L266) and we don't allow non-free libraries.

Could your app work without this plugin?

**Comment by LaMonF** [comment]
@Rudloff Yes, this is the old but default plugin provided by ionic : https://ionicframework.com/docs/native/geofence/ . Unfortunately we are not responsible for the packaging of this library. 

I am not aware of another library to provide the same features on ionic.

The app might works without this library, but it will miss some features obviously.

**Comment by Rudloff** [comment]
> Unfortunately we are not responsible for the packaging of the of this library.

[I asked upstream about this](https://github.com/cowbell/cordova-plugin-geofence/issues/290), but the latest release was almost 2 years ago so I would not count on it.

> The app might work without this library, but it will miss some features obviously.

Do you think it would be possible to remove this plugin from the F-Droid branch?
I would understand if it is too much work for you, but without that, I am afraid we won't be able to package your app.

**Comment by Sispheor** [comment]
Not really a good idea from my point of view to remove features just to be available on this alternative store.

**Comment by NextDev65** [comment]
Is it doable to remove the plugin just for the fdroid version?

**Comment by Sispheor** [comment]
Like I said. We are not going to create dedicated version in order to be compliant with an alternative store.
